//
//  DecodingTests.swift
//  JikanSwift
//
//  Created by Никита Гузарский on 24.03.2026.
//

import XCTest
@testable import JikanSwift

final class DecodingTests: XCTestCase {

    private let decoder = JSONDecoder()

    // MARK: – Helpers

    /// Loads a JSON fixture by name.
    ///
    /// Tries multiple strategies so the tests work regardless of whether
    /// you run them via `swift test` (SPM) or from Xcode:
    ///
    /// 1. `Bundle.module`       — auto-generated by SPM when the target
    ///                            declares `resources:` in Package.swift.
    /// 2. `Bundle(for: Self)`   — Xcode-managed test bundle (when the
    ///                            Fixtures folder is added to the test target
    ///                            via Target Membership).
    /// 3. Relative file path    — fallback that walks up from `#file` to
    ///                            find the Fixtures directory in the source tree.
    private func fixtureData(_ name: String) throws -> Data {

        // Strategy 1 — SPM resource bundle (auto-generated when target has resources)
        // SWIFT_PACKAGE is defined automatically by the Swift Package Manager.
        #if SWIFT_PACKAGE
        if let url = Bundle.module.url(
            forResource: name,
            withExtension: "json",
            subdirectory: "Fixtures"
        ) {
            return try Data(contentsOf: url)
        }
        #endif

        // Strategy 2 — Xcode test bundle (when Fixtures folder is in Target Membership)
        if let url = Bundle(for: type(of: self)).url(
            forResource: name,
            withExtension: "json",
            subdirectory: "Fixtures"
        ) {
            return try Data(contentsOf: url)
        }

        // Strategy 3 — resolve from source tree relative to this file
        let thisFile = URL(fileURLWithPath: #filePath)
        let fixturesDir = thisFile
            .deletingLastPathComponent()          // JikanSwiftTests/
            .appendingPathComponent("Fixtures")
        let fileURL = fixturesDir.appendingPathComponent("\(name).json")

        guard FileManager.default.fileExists(atPath: fileURL.path) else {
            throw NSError(
                domain: "DecodingTests",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey:
                    "Fixture \(name).json not found. Searched Bundle.module, " +
                    "Bundle(for:), and \(fixturesDir.path)"]
            )
        }
        return try Data(contentsOf: fileURL)
    }

    // MARK: – Anime search response

    func testDecodeAnimeSearchResponse() throws {
        let data = try fixtureData("anime_search")
        let response = try decoder.decode(JikanResponse<AnimeBrief>.self, from: data)

        XCTAssertEqual(response.data.count, 2)
        XCTAssertEqual(response.data[0].title, "Naruto")
        XCTAssertEqual(response.data[0].id, 20)
        XCTAssertEqual(response.data[1].title, "Naruto: Shippuuden")
        XCTAssertEqual(response.data[1].id, 1735)
    }

    func testSearchResponsePagination() throws {
        let data = try fixtureData("anime_search")
        let response = try decoder.decode(JikanResponse<AnimeBrief>.self, from: data)
        let pagination = try XCTUnwrap(response.pagination)

        XCTAssertEqual(pagination.hasNextPage, true)
        XCTAssertEqual(pagination.lastVisiblePage, 5)
        XCTAssertEqual(pagination.currentPage, 1)
    }

    func testSearchResponsePaginationItems() throws {
        let data = try fixtureData("anime_search")
        let response = try decoder.decode(JikanResponse<AnimeBrief>.self, from: data)
        let items = try XCTUnwrap(response.pagination?.items)

        XCTAssertEqual(items.count, 25)
        XCTAssertEqual(items.total, 120)
        XCTAssertEqual(items.perPage, 25)
    }

    func testAnimeBriefImages() throws {
        let data = try fixtureData("anime_search")
        let response = try decoder.decode(JikanResponse<AnimeBrief>.self, from: data)
        let first = response.data[0]

        XCTAssertNotNil(first.images?.jpg?.imageURL)
        XCTAssertNotNil(first.images?.jpg?.smallImageURL)
        XCTAssertNotNil(first.images?.jpg?.largeImageURL)
        XCTAssertNotNil(first.images?.webp)
    }

    func testAnimeBriefFieldValues() throws {
        let data = try fixtureData("anime_search")
        let response = try decoder.decode(JikanResponse<AnimeBrief>.self, from: data)
        let naruto = response.data[0]

        XCTAssertEqual(naruto.type, "TV")
        XCTAssertEqual(naruto.source, "Manga")
        XCTAssertEqual(naruto.episodes, 220)
        XCTAssertEqual(naruto.status, "Finished Airing")
        XCTAssertEqual(naruto.score, 8.0)
        XCTAssertEqual(naruto.rank, 500)
        XCTAssertEqual(naruto.popularity, 10)
        XCTAssertNotNil(naruto.synopsis)
    }

    // MARK: – Anime details response

    func testDecodeAnimeDetailsResponse() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)
        let anime = response.data

        XCTAssertEqual(anime.id, 1)
        XCTAssertEqual(anime.title, "Cowboy Bebop")
        XCTAssertEqual(anime.titleEnglish, "Cowboy Bebop")
        XCTAssertEqual(anime.titleJapanese, "カウボーイビバップ")
        XCTAssertEqual(anime.episodes, 26)
        XCTAssertEqual(anime.score, 8.75)
        XCTAssertEqual(anime.year, 1998)
        XCTAssertEqual(anime.season, "spring")
    }

    func testAnimeDetailsAiringFlag() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)

        XCTAssertEqual(response.data.airing, false)
        XCTAssertEqual(response.data.status, "Finished Airing")
    }

    func testAnimeDetailsAired() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)
        let aired = try XCTUnwrap(response.data.aired)

        XCTAssertEqual(aired.string, "Apr 3, 1998 to Apr 24, 1999")
        XCTAssertNotNil(aired.from)
        XCTAssertNotNil(aired.to)
    }

    func testAnimeDetailsTrailer() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)
        let trailer = try XCTUnwrap(response.data.trailer)

        XCTAssertEqual(trailer.youtubeId, "qig4KOK2R2g")
        XCTAssertNotNil(trailer.url)
        XCTAssertNotNil(trailer.embedUrl)
    }

    func testAnimeDetailsGenres() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)
        let genres = try XCTUnwrap(response.data.genres)

        XCTAssertEqual(genres.count, 2)
        XCTAssertEqual(genres[0].name, "Action")
        XCTAssertEqual(genres[0].id, 1)
        XCTAssertEqual(genres[1].name, "Award Winning")
    }

    func testAnimeDetailsStudios() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)
        let studios = try XCTUnwrap(response.data.studios)

        XCTAssertEqual(studios.count, 1)
        XCTAssertEqual(studios[0].name, "Sunrise")
    }

    func testAnimeDetailsTitleSynonyms() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)

        XCTAssertEqual(response.data.titleSynonyms, ["CB"])
    }

    func testAnimeDetailsRatingAndDuration() throws {
        let data = try fixtureData("anime_details")
        let response = try decoder.decode(JikanSingleResponse<AnimeDetails>.self, from: data)

        XCTAssertEqual(response.data.rating, "R - 17+ (violence & profanity)")
        XCTAssertEqual(response.data.duration, "24 min per ep")
    }

    // MARK: – Edge cases

    func testDecodingInvalidJSONThrows() {
        let garbage = "{ not json }".data(using: .utf8)!

        XCTAssertThrowsError(
            try decoder.decode(JikanResponse<AnimeBrief>.self, from: garbage)
        )
    }

    func testEmptyDataArrayDecodes() throws {
        let json = """
        { "data": [], "pagination": { "last_visible_page": 0, "has_next_page": false } }
        """.data(using: .utf8)!

        let response = try decoder.decode(JikanResponse<AnimeBrief>.self, from: json)
        XCTAssertTrue(response.data.isEmpty)
        XCTAssertEqual(response.pagination?.hasNextPage, false)
    }
}
